openapi: 3.0.1
info:
  title: LoanBenefits
  description: API used to retrieve Loan Benefits
  termsOfService: https://FirstData.com/
  contact:
    name: First Data Education
    url: https://FirstData.com/
  license:
    name: First Data Education License
    url: https://FirstData.com/
  version: v1
paths:
  '/api/v1/loanbenefits/{personId}':
    get:
      tags:
        - LoanBenefits
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanBenefit'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanBenefit'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoanBenefit'
        default:
          description: Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Loan Benefits
  '/api/v1/loanbenefits/{personId}/{loanId}':
    get:
      tags:
        - LoanBenefits
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: loanId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/LoanBenefit'
            application/json:
              schema:
                $ref: '#/components/schemas/LoanBenefit'
            text/json:
              schema:
                $ref: '#/components/schemas/LoanBenefit'
        default:
          description: Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Loan Benefit by Loan
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    LoanBenefit:
      type: object
      properties:
        description:
          type: string
          nullable: true
        id:
          type: string
          nullable: true
        monthsRemaining:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
        statusEffectiveDate:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
