openapi: 3.0.1
info:
  title: Permissions
  description: "The Permissions REST API is used to retrieve and update a users permissions by type. You can get all permissions or a specific type and you can also retrieve the history of the last update made. When updating the permissions the type and the value are required.\n\n**Example values:**\n```\n{\n\t\"type\": \"AffiliateShareMarketing\",\n\t\"value\": true,\n\t\"lastUpdateDateTime\": \"2021-03-25T10:40:56.393356Z\",\n\t\"isDefault\": true\n}\n```\n\n**BAL Permissions REST API FAQ:**\n1) Fiserv accepts a Boolean (True/False) value for these fields : Email1098, EmailRegulatory, EmailNonRegulatory, EmailMarketing, PhoneMarketing, USPSMarketing, AffiliateShareMarketing\n\n\ti) If Paperless is selected, we would pass TRUE for the fields \"Email1098, EmailRegulatory, EmailNonRegulatory\n\n\t* A: \"true\" should be passed.\n\n\tii) If Paper is selected, we would pass FALSE for the fields \"Email1098, EmailRegulatory, EmailNonRegulatory\"\n\n\t* A: \"false\" should be passed.\n\n\tiii) When we make a GET call on the Permissions API, would we always get back all TRUE (or all FALSE) for Email1098, EmailRegulatory, EmailNonRegulatory? And not a mix of TRUE and FALSE values?\n\n\t* A:  Whatever the values are would be returned.  (That could be a mix of values, \"true\" or \"false\".)\n2) What is AffiliateShareMarketing?\n\n\t* A: This isn't used any more.\n3) Is Text marketing the same as \"PhoneMarketing\" in the API?\n\n\t* A: No. (Text marketing is supported by the Phone API.)"
  termsOfService: https://FirstData.com/
  contact:
    name: First Data Education
    url: https://FirstData.com/
  license:
    name: First Data Education License
    url: https://FirstData.com/
  version: v1
paths:
  '/api/v1/persons/{personId}/permissions':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Permission'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permissions
  '/api/v1/persons/{personId}/permissions/{type}':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Permission'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permission by Type
    put:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
          text/json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
          application/*+json:
            schema:
              $ref: '#/components/schemas/ChangePermission'
      responses:
        '204':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Update Permission
  '/api/v1/persons/{personId}/permissions/{type}/history':
    get:
      tags:
        - Permissions
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PermissionType'
        - name: offset
          in: query
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Page`1'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Permission History by Type
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    PermissionType:
      enum:
        - Email1098
        - EmailRegulatory
        - EmailNonRegulatory
        - EmailMarketing
        - PhoneMarketing
        - USPSMarketing
        - AffiliateShareMarketing
      type: string
    PermissionValue:
      enum:
        - Yes
        - No
        - NonEsign
      type: string
    Permission:
      type: object
      properties:
        isDefault:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
        type:
          $ref: '#/components/schemas/PermissionType'
        value:
          $ref: '#/components/schemas/PermissionValue'
      additionalProperties: false
    ChangePermission:
      required:
        - value
      type: object
      properties:
        value:
          $ref: '#/components/schemas/PermissionValue'
      additionalProperties: false
    ChangeHistory:
      type: object
      properties:
        hasValueChanged:
          type: boolean
        updateDateTime:
          type: string
          format: date-time
        value:
          $ref: '#/components/schemas/PermissionValue'
      additionalProperties: false
    Page`1:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ChangeHistory'
          nullable: true
        limit:
          type: integer
          format: int32
        offset:
          type: integer
          format: int32
        totalCount:
          type: integer
          format: int32
      additionalProperties: false
x-error-codes:
  PRM4004:
    Title: Permission record not found.
  PRM5000:
    Title: Permission type is invalid.
  PRM5001:
    Title: Permission value is invalid.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.
  GBL5004:
    Title: Client ID not authorized to update information on the person.