openapi: 3.0.1
info:
  title: Phones
  description: "The Phones REST API is used to retrieve all (active and inactive) phone numbers, retrieve a specific phone number by phone id, update a phone number by phone id, and you can also add a new phone number to the person. When adding a new phone number, both number and type are required. When updating an existing phone number the following are required: last update date, phone number, status, and type. The last update date needs to be used from the GET call. You can add the following phone filters: status, type, isPrimary, and isWorkPhoneNumber as query parameters to further refine your results.\n\n**Example Values:**\n\n{\n\n\"id\": \"57401767\",\n\n\"number\": \"5553484085\",\n\n\"status\": \"Bad\",\n\n\"isPrimary\": false,\n\n\"type\": \"Land\",\n\n\"isWorkPhoneNumber\": false,\n\n\"consents\": {\n\t\t\"autoDial\": {\n\t\t\t\"hasConsent\": false\n\t\t},\n\t\t\"text\": {\n\t\t\t\"hasConsent\": false\n\t\t}\n\t}\n\n\"lastUpdateDateTime\": \"2021 - 11 - 04T18:33:23Z\"\n\n}\n\n\n**BAL Phones REST API FAQ:**\n1) Where do we get the AutoDialConsentReason value from?\n\n\t A: The API is expecting one of these \"NoCustomerResponse, ConsentGiven, ConsentNotGiven, Litigation\"\n2) For TextConsent, are the acceptable values TRUE, FALSE?\n\n\t A: The acceptable values are \"true\" or \"false\"\n3) Would AutoDialConsent and TextConsent options cover all TCPA requirements?\n\n\t A: Processes need to be in place to use these values unless there is a legal reason why they don't have to be.\n4) Where do we get the PhoneStatus of \"Good, Bad, Disconnect\"?\n\n\t A: The current values will be returned from the GET action of the Phones API\n5) How do I only get \"good\" numbers?\n\n\t A: /phones/api/v1/persons/[personid]/phones?status=good\n6) How do I only get the primary number?\n\n\t A: /phones/api/v1/persons/[personid]/phones?isPrimary=true\n7) How do I only get \"land\" numbers?\n\n\t A: /phones/api/v1/persons/[personid]/phones?Type=Land\n\n\t *NOTE: Other phone type filter options: Cell, Land, Wireless, Pager, Fax, Foreign*\n8) How do I only get work numbers?\n\n\t A: /phones/api/v1/persons/[personid]/phones?isWorkPhoneNumber=true*\n9) How many active phone numbers can be stored for the customer?\n\n\t A: Unlimited"
  termsOfService: https://FirstData.com/
  contact:
    name: First Data Education
    url: https://FirstData.com/
  license:
    name: First Data Education License
    url: https://FirstData.com/
  version: v1
paths:
  '/api/v1/persons/{personId}/phones':
    get:
      tags:
        - Phones
      summary: Retrieves a specific users phone list.
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/PhoneType'
        - name: status
          in: query
          schema:
            $ref: '#/components/schemas/PhoneStatus'
        - name: isPrimary
          in: query
          schema:
            type: boolean
            nullable: true
        - name: isWorkPhoneNumber
          in: query
          schema:
            type: boolean
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: If the person is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Returns the specified user's phone
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Phone'
        default:
          description: Default error response for unlisted http status codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Phones
    post:
      tags:
        - Phones
      summary: Creates a new Phone for the specified user.
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddPhone'
          text/json:
            schema:
              $ref: '#/components/schemas/AddPhone'
          application/*+json:
            schema:
              $ref: '#/components/schemas/AddPhone'
      responses:
        default:
          description: Default error response for unlisted http status codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '201':
          description: Returns the newly created phone.
          headers:
            Location:
              description: Location of the newly created resource
              schema:
                type: string
                description: Location of the newly created resource
                format: ''
        '404':
          description: If the person is not found.
      x-proxy-name: Add Phone
  '/api/v1/persons/{personId}/phones/{phoneId}':
    get:
      tags:
        - Phones
      summary: Retrieve the specified phone for the specified person
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: phoneId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      responses:
        '404':
          description: If the phone is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '200':
          description: Returns the specified person's phone
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Phone'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Get Phone
    put:
      tags:
        - Phones
      summary: Update a Phone for the specified user.
      parameters:
        - name: personId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: phoneId
          in: path
          required: true
          schema:
            type: string
            nullable: true
        - name: X-Correlation-ID
          in: header
          description: Correlation Id for the request
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePhone'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdatePhone'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdatePhone'
      responses:
        '204':
          description: Success
        '404':
          description: If the person is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        default:
          description: Default error response for unlisted http status codes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      x-proxy-name: Update Phone
components:
  schemas:
    PhoneType:
      enum:
        - Cell
        - Land
        - Wireless
        - Pager
        - Fax
        - Foreign
      type: string
    PhoneStatus:
      enum:
        - Good
        - Bad
        - Disconnect
      type: string
    ProblemDetails:
      type: object
      properties:
        code:
          type: string
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        title:
          type: string
          nullable: true
        traceId:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties:
        type: object
        additionalProperties: false
    AutoDialConsentReason:
      enum:
        - NoCustomerResponse
        - ConsentGiven
        - ConsentNotGiven
        - Litigation
      type: string
    AutoDialConsent:
      type: object
      properties:
        hasConsent:
          type: boolean
        lastVerifiedDateTime:
          type: string
          format: date-time
          nullable: true
        reason:
          $ref: '#/components/schemas/AutoDialConsentReason'
      additionalProperties: false
    TextConsent:
      type: object
      properties:
        hasConsent:
          type: boolean
        lastVerifiedDateTime:
          type: string
          format: date-time
          nullable: true
      additionalProperties: false
    Consents:
      type: object
      properties:
        autoDial:
          $ref: '#/components/schemas/AutoDialConsent'
        text:
          $ref: '#/components/schemas/TextConsent'
      additionalProperties: false
    Phone:
      type: object
      properties:
        consents:
          $ref: '#/components/schemas/Consents'
        extension:
          type: string
          nullable: true
        id:
          type: string
          nullable: true
        isPrimary:
          type: boolean
        isWorkPhoneNumber:
          type: boolean
        lastUpdateDateTime:
          type: string
          format: date-time
        number:
          type: string
          nullable: true
        status:
          $ref: '#/components/schemas/PhoneStatus'
        type:
          $ref: '#/components/schemas/PhoneType'
      additionalProperties: false
    ChangeAutoDialConsent:
      type: object
      properties:
        reason:
          $ref: '#/components/schemas/AutoDialConsentReason'
      additionalProperties: false
    ChangeTextConsent:
      type: object
      properties:
        hasConsent:
          type: boolean
      additionalProperties: false
    ChangeConsents:
      type: object
      properties:
        autoDial:
          $ref: '#/components/schemas/ChangeAutoDialConsent'
        text:
          $ref: '#/components/schemas/ChangeTextConsent'
      additionalProperties: false
    AddPhone:
      required:
        - number
        - type
      type: object
      properties:
        consents:
          $ref: '#/components/schemas/ChangeConsents'
        extension:
          maxLength: 7
          type: string
          nullable: true
        isPrimary:
          type: boolean
          default: false
        isWorkPhoneNumber:
          type: boolean
          default: false
        number:
          minLength: 10
          pattern: '^[0-9]+$'
          type: string
        type:
          $ref: '#/components/schemas/PhoneType'
      additionalProperties: false
    UpdatePhone:
      required:
        - lastUpdateDateTime
        - number
        - status
        - type
      type: object
      properties:
        consents:
          $ref: '#/components/schemas/ChangeConsents'
        extension:
          maxLength: 7
          type: string
          nullable: true
        isPrimary:
          type: boolean
          default: false
        isWorkPhoneNumber:
          type: boolean
          default: false
        lastUpdateDateTime:
          type: string
          format: date-time
        number:
          minLength: 10
          pattern: '^[0-9]+$'
          type: string
        status:
          $ref: '#/components/schemas/PhoneStatus'
        type:
          $ref: '#/components/schemas/PhoneType'
      additionalProperties: false
x-error-codes:
  PHO4004:
    Title: Phone record not found.
  PHO4009:
    Title: The Phone Number for an existing record cannot be changed.
  PHO4010:
    Title: Phone record with submitted number already exists.
  PHO4011:
    Title: The LastUpdateDateTime is not the latest.
  GBL4000:
    Title: Invalid request.
  GBL4004:
    Title: Person not found.
  GBL5000:
    Title: An unexpected error was encountered.
  GBL5003:
    Title: System not available.
  GBL5004:
    Title: Client ID not authorized to update information on the person.